.TH CHKSUM-CLI 1
.SH NAME
chksum-cli \- simple checksum calculator
.SH SYNOPSIS
.B chksum-cli
[OPTIONS]
.IR PATH ...
.SH DESCRIPTION
Calculates checksum of files and directories under given PATH(s).
.SH OPTIONS
.BR \-h ", " \-\-help
Prints help information.
.TP
.BI \-H " HASH" "\fR, \fP\-\-hash=" HASH
Choose hashing algorithm.
.TP
.BI \-s " SIZE" "\fR, \fP\-\-chunk\-size=" SIZE
Set chunk size of processing data.
.TP
.BR \-V ", " \-\-version
Prints version information.
.SH HASHES
.R MD5, SHA-1, SHA-2 256
.SH SEE ALSO
.BR md5sum "(1), " sha1sum "(1), " sha256sum "(1)"
.SH BUGS
.R See https://github.com/ventaquil/chksum/issues for issues.
