[package]
name = "chksum"
description = "Easy way to make checksum of single file or whole directory."
version = "0.0.0"
authors = ["Konrad Goławski <konrad@golawski.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2"
walkdir = "~2"
