[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "format"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "fmt"
command = "cargo"
args = ["fmt", "--", "--check"]
dependencies = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]
