combine_control_expr = false
edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
