[package]
name = "chksum-arch"
version = "0.1.0-rc1"
authors = ["Konrad Goławski <konrad@golawski.it>"]
edition = "2021"
rust-version = "1.58.0"
description = ""
readme = ""
repository = "https://github.com/ventaquil/chksum"
license = "MIT"
keywords = ["parallel processing", "simd"]
categories = ["hardware-support"]

[dependencies]
chksum-traits = { path = "../chksum-traits", default-features = false, features = ["std"] }

[features]
default = []
simd = []
