[package]
name = "chksum"
version = "0.1.0-rc1"
authors = ["Konrad Goławski <konrad@golawski.it>"]
edition = "2021"
rust-version = "1.58.0"
description = "A simple to use library which allows to make checksum of single file or whole directory."
readme = "README.md"
repository = "https://github.com/ventaquil/chksum"
license = "MIT"
keywords = ["checksum", "directory-checksum", "file-checksum", "hash"]
categories = ["algorithms", "cryptography", "filesystem"]

[dependencies]
chksum-arch = { path = "../chksum-arch", default-features = false }
chksum-config = { path = "../chksum-config", default-features = false }
chksum-hash = { path = "../chksum-hash", default-features = false, features = ["std"] }
chksum-sync = { path = "../chksum-sync", default-features = false, optional = true }
chksum-traits = { path = "../chksum-traits", default-features = false, features = ["std"] }

[features]
default = []
sync = ["chksum-sync"]
