.TH CHKSUM 1
.SH NAME
chksum \- simple checksum calculator
.SH SYNOPSIS
.B chksum
[OPTIONS]
.IR PATHNAME ...
.SH DESCRIPTION
Calculates checksum of files and directories under given PATHNAME(s).
.SH OPTIONS
.BR \-h ", " \-\-help
Prints help information.
.TP
.BR \-V ", " \-\-version
Prints version information.
.TP
.BI \-s " SIZE" "\fR, \fP\-\-chunk\-size=" SIZE
Chunk size.
.TP
.BI \-H " HASH" "\fR, \fP\-\-hash=" HASH
Chosen hash algorithm.
.TP
.BI \-w " WORKERS" "\fR, \fP\-\-workers=" WORKERS
Maximum number of working threads.
.TP
.BR \-W ", " \-\-with\-pathnames
Use pathnames to calculate digests.
.SH HASHES
.R MD5, SHA-1
.SH SEE ALSO
.BR md5sum "(1), " sha1sum (1)
.SH BUGS
.R See https://github.com/ventaquil/chksum/issues for issues.
